import io.ktor.util.collections.setValue

plugins {
	id("mod-platform")
	id("net.minecraftforge.gradle")
	id("net.minecraftforge.renamer") version "1.0.14"
	id("net.minecraftforge.jarjar") version "0.2.3"
}

platform {
	loader = "forge"
	dependencies {
		required("minecraft") {
			forgeVersionRange = "[${prop("mc_version_range")}]"
		}
		required("forge") {
			forgeVersionRange = "[1,)"
		}
	}
}

if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {

	renamer.enableMixinRefmaps {
		// Test source set SHOULDN'T be used for the refmaps (circular dependencies with kotlin for some reason)
		config("${prop("mod_id")}.mixins.json")
		source(sourceSets.main.get(), prop("mod_id"))
		jar(project.tasks.named(JavaPlugin.JAR_TASK_NAME, Jar::class.java))
	}

	afterEvaluate {
		minecraft.runs.forEach { r ->
			renamer.mixin.run(r)
		}
	}

	renamer.classes(tasks.named<Jar>("jar")) {
		output.set(tasks.named<Jar>("jar").get().archiveFile)
		dependsOn("jarJar")
		// We need to use the generated mappings, which includes things generated by the annotation processor
		mappings(renamer.mixin.generatedMappings)
	}

	// Fixes the maven publishing using a broken jar
	tasks.named<Jar>("sourcesJar") {
		dependsOn("renameJar")
	}
}

// This methods registers jarJar for the default jar task.
// The closure allows you to configure the task, instead of needing to do this:
// tasks.named<net.minecraftforge.jarjar.gradle.JarJar>("jarJar")
jarJar.register() {
	archiveClassifier = null
}

tasks.named<Jar>("jar") {
	from(project.file(platform.atFile)) {
		into("META-INF")
		rename { "accesstransformer.cfg" }
	}
}

minecraft {
	mappings("official", stonecutter.current.version)

	version = "${stonecutter.current.version}-${property("forge_version")}"

	//validateAccessTransformers = true

	accessTransformers = files(project.file(platform.atFile))

	runs {
		configureEach {
			workingDir.convention(layout.projectDirectory.dir("run"))
		}

		register("client") {
			systemProperty("forge.enabledGameTestNamespaces", prop("mod_id"))
			args("--mixin.config", "${prop("mod_id")}.mixins.json")
//			client()
//			gameDirectory = file("run/")
//			ideName = "Forge Client (${stonecutter.active?.version})"
//			programArgument("--username=Dev")
		}
		register("server") {
//			server()
//			gameDirectory = file("run/")
//			ideName = "Forge Server (${stonecutter.active?.version})"
		}
	}


//	mods {
//		register(prop("mod_id")) {
//			sourceSet(sourceSets["main"])
//		}
//	}
}

repositories {
	mavenCentral()
	minecraft.mavenizer(this) // In Kotlin, it = this
	maven(fg.forgeMaven)
	maven(fg.minecraftLibsMaven)
	strictMaven("https://api.modrinth.com/maven", "maven.modrinth") { name = "Modrinth" }
	maven("https://raw.githubusercontent.com/Kyubion-Studios/Mod-Resources/main/maven/") { name = "Kyubion Mod Resources" }
	maven("https://maven.isxander.dev/releases")
}

dependencies {
	implementation(minecraft.dependency("net.minecraftforge:forge:${stonecutter.current.version}-${prop("forge_version")}"))
	if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {
		annotationProcessor("org.spongepowered:mixin:${libs.versions.mixin.get()}:processor")
	}
	//implementation(libs.moulberry.mixinconstraints)
	api("jarJar"(prop("sdl_dependency")) as Any)
	api("wily.factory_api:factory_api-forge:${stonecutter.current.version}-${prop("factory_api_version")}")
	compileOnly("maven.modrinth:world-host:${prop("world_host_version")}")
	compileOnly("maven.modrinth:vivecraft:${prop("vivecraft_version")}")
	api("jarJar"("org.apache.httpcomponents:httpclient:4.5.14") {
		exclude(group = "commons-codec", module = "commons-codec")
	} as Any)
	api("jarJar"("org.apache.httpcomponents:httpcore:4.4.16") as Any)
	api("jarJar"("commons-logging:commons-logging:1.2") as Any)
}

if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {
	renamer.mappings(minecraft.dependency.toSrg)
}

sourceSets {
	main {
		resources.srcDir(
			"${rootDir}/versions/datagen/${stonecutter.current.version.split("-")[0]}/src/main/generated"
		)
	}
}

tasks.withType<Javadoc> {
	enabled = false
}
