package wily.legacy.client.control.tooltip;

import com.mojang.blaze3d.platform.InputConstants;
import wily.factoryapi.base.ArbitrarySupplier;
import wily.legacy.Legacy4JClient;
import wily.legacy.client.control.ControlType;
import wily.legacy.client.control.ControllerBinding;
import wily.legacy.client.control.LegacyKeyMapping;

import java.util.HashMap;
import java.util.Map;

public class CommonIcon {
    public static final Map<String, ArbitrarySupplier<ComponentIcon>> commonIcons = new HashMap<>();
    public static final ArbitrarySupplier<ComponentIcon> PLAYER_MOVEMENT = registerCommonComponentIcon("player_movement", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_W), ControlTooltip.getKeyIcon(InputConstants.KEY_A), ControlTooltip.getKeyIcon(InputConstants.KEY_S), ControlTooltip.getKeyIcon(InputConstants.KEY_D)) : ControllerBinding.LEFT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> MENU_QUICK_ACTION = registerCommonComponentIcon("menu_quick_action", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.MOUSE_BUTTON_LEFT), ControlTooltip.PLUS_ICON, ControlTooltip.getKeyIcon(InputConstants.KEY_LSHIFT)) : ControllerBinding.UP_BUTTON.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> NAVIGATION = registerCommonComponentIcon("navigation", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_UP), ControlTooltip.getKeyIcon(InputConstants.KEY_LEFT), ControlTooltip.getKeyIcon(InputConstants.KEY_DOWN), ControlTooltip.getKeyIcon(InputConstants.KEY_RIGHT)) : ControllerBinding.LEFT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> HORIZONTAL_NAVIGATION = registerCommonComponentIcon("horizontal_navigation", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_LEFT), ControlTooltip.getKeyIcon(InputConstants.KEY_RIGHT)) : ControllerBinding.LEFT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> VERTICAL_NAVIGATION = registerCommonComponentIcon("vertical_navigation", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_UP), ControlTooltip.getKeyIcon(InputConstants.KEY_DOWN)) : ControllerBinding.LEFT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> CONTROL_PAGE = registerCommonComponentIcon("control_page", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_LSHIFT), ControlTooltip.PLUS_ICON, CompoundComponentIcon.of(ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuPageLeft).getKey().getValue()), ControlTooltip.SPACE_ICON, ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuPageRight).getKey().getValue()))) : ControllerBinding.RIGHT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> CONTROL_TAB = registerCommonComponentIcon("control_tab", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabLeft).getKey().getValue()), ControlTooltip.SPACE_ICON, ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabRight).getKey().getValue())) : CompoundComponentIcon.of(ControllerBinding.LEFT_BUMPER.getIcon(), ControlTooltip.SPACE_ICON, ControllerBinding.RIGHT_BUMPER.getIcon()));
    public static final ArbitrarySupplier<ComponentIcon> CONTROL_TYPE = registerCommonComponentIcon("control_type", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_LSHIFT), ControlTooltip.PLUS_ICON, CompoundComponentIcon.of(ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabLeft).getKey().getValue()), ControlTooltip.SPACE_ICON, ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabRight).getKey().getValue()))) : CompoundComponentIcon.of(ControllerBinding.LEFT_TRIGGER.getIcon(), ControlTooltip.SPACE_ICON, ControllerBinding.RIGHT_TRIGGER.getIcon()));
    public static final ArbitrarySupplier<ComponentIcon> LEFT_CRAFTING_TYPE = registerCommonComponentIcon("left_crafting_type", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_LSHIFT), ControlTooltip.PLUS_ICON, ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabLeft).getKey().getValue())) : ControllerBinding.LEFT_TRIGGER.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> RIGHT_CRAFTING_TYPE = registerCommonComponentIcon("right_crafting_type", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_LSHIFT), ControlTooltip.PLUS_ICON, ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabRight).getKey().getValue())) : ControllerBinding.RIGHT_TRIGGER.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> BUNDLE_SELECTION = registerCommonComponentIcon("bundle_selection", () -> ControlType.getActiveType().isKbm() ? CompoundComponentIcon.of(ControlTooltip.getKeyIcon(InputConstants.KEY_1), ControlTooltip.SPACE_ICON, ControlTooltip.getKeyIcon(InputConstants.KEY_9), ControlTooltip.SPACE_ICON, ControlTooltip.getKbmIcon(ControlTooltip.MOUSE_BASE_CHAR)) : ControllerBinding.RIGHT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> PRESS = registerCommonComponentIcon("press", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(InputConstants.KEY_RETURN) : ControllerBinding.DOWN_BUTTON.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> OPTION = registerCommonComponentIcon("option", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(InputConstants.KEY_O) : ControllerBinding.UP_BUTTON.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> EXTRA = registerCommonComponentIcon("extra", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(InputConstants.KEY_X) : ControllerBinding.LEFT_BUTTON.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> POINTER_MOVEMENT = registerCommonComponentIcon("pointer_movement", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKbmIcon(ControlTooltip.MOUSE_BASE_CHAR) : ControllerBinding.LEFT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> CAMERA_MOVEMENT = registerCommonComponentIcon("camera_movement", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKbmIcon(ControlTooltip.MOUSE_BASE_CHAR) : ControllerBinding.LEFT_STICK.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> MENU_MAIN_ACTION = registerCommonComponentIcon("menu_main_action", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(InputConstants.MOUSE_BUTTON_LEFT) : ControllerBinding.DOWN_BUTTON.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> MENU_OFF_ACTION = registerCommonComponentIcon("menu_off_action", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(InputConstants.MOUSE_BUTTON_RIGHT) : ControllerBinding.LEFT_BUTTON.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> LEFT_TAB = registerCommonComponentIcon("left_tab", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabLeft).getKey().getValue()) : ControllerBinding.LEFT_BUMPER.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> RIGHT_TAB = registerCommonComponentIcon("right_tab", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(LegacyKeyMapping.of(Legacy4JClient.keyMenuTabRight).getKey().getValue()) : ControllerBinding.RIGHT_BUMPER.getIcon());
    public static final ArbitrarySupplier<ComponentIcon> CANCEL_BINDING = registerCommonComponentIcon("cancel_binding", () -> ControlType.getActiveType().isKbm() ? ControlTooltip.getKeyIcon(InputConstants.KEY_ESCAPE) : ControllerBinding.BACK.getIcon());

    public static ArbitrarySupplier<ComponentIcon> registerCommonComponentIcon(String key, ArbitrarySupplier<ComponentIcon> supplier) {
        commonIcons.put(key, supplier);
        return supplier;
    }
}
