name: Bug/Glitch Report
title: "[Bug/Glitch]"
description: "General template for Bugs and Glitches report"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Follow this template if you want support/fix to be faster.
  - type: input
    id: mod-version
    attributes:
      label: "Legacy4J Version"
      description: "The specific used mod version"
      placeholder: "Example 1.20.6-1.7"
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      placeholder: "Example: NeoForge 20.6.98-beta or Fabric Loader 0.14.21"
    validations:
      required: false
 
  - type: markdown
    attributes:
      value: "## Description"

  - type: textarea
    id: bug-context
    attributes:
      label: Bug/Glitch Occurrence Context
    validations:
      required: true
  
  - type: input
    id: crash-report
    attributes:
      label: Crash Report
      description: "Paste here the link(Ex: Pastebin or mclo.gs) or the specific part of the issue if you are sure"
    validations:
      required: false

  - type: textarea
    id: whw
    attributes:
      label: What happened wrong?
    validations:
      required: true
