name: Bug Report
title: "[Bug/Glitch]"
description: "General template for Bugs and Glitches report"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Follow this template if you want support/fix to be faster.
  - type: input
    id: mod-version
    attributes:
      label: "Legacy4J Version"
      description: "The specific mod version"
      placeholder: "Example: 1.21.10-1.8.7"
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      placeholder: "Example: NeoForge 21.10.64 or Fabric Loader 0.18.5"
    validations:
      required: true
 
  - type: markdown
    attributes:
      value: "## Description"

  - type: textarea
    id: bug-context
    attributes:
      label: Context of the bug
    validations:
      required: true
  
  - type: input
    id: crash-report
    attributes:
      label: Crash Report
      description: "Paste the link of your log here, using an applicable site (ie: mclo.gs). If you are not sure, mark N/A"
    validations:
      required: true

  - type: textarea
    id: www
    attributes:
      label: What went wrong?
    validations:
      required: true
