package wily.legacy.util;

import net.minecraft.resources.ResourceLocation;
import wily.legacy.Legacy4J;

public class LegacySprites {
    public static final ResourceLocation ENCHANTING_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/enchanting_slot");
    public static final ResourceLocation LEADERBOARD_BUTTON = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/leaderboard_button");
    public static final ResourceLocation LEADERBOARD_BUTTON_HIGHLIGHTED = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/leaderboard_button_highlighted");
    public static final ResourceLocation PANEL_HIGHLIGHT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/panel_highlight");
    public static final ResourceLocation DISCOUNT_STRIKETHRUOGH_SPRITE = ResourceLocation.withDefaultNamespace("container/villager/discount_strikethrough");
    public static final ResourceLocation NON_INTERACTIVE_RESULT_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/non_interactive_result_slot");
    public static final ResourceLocation CRAFTER_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/crafter_slot");
    public static final ResourceLocation DISABLED_CRAFTER_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/disabled_crafter_slot");
    public static final ResourceLocation BUTTON_SLOT_SELECTED = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/button_slot_selected");
    public static final ResourceLocation BUTTON_SLOT_HIGHLIGHTED = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/button_slot_highlighted");
    public static final ResourceLocation BUTTON_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/button_slot");
    public static final ResourceLocation BANNER_SLOT = ResourceLocation.withDefaultNamespace("container/loom/banner_slot");
    public static final ResourceLocation DYE_SLOT = ResourceLocation.withDefaultNamespace("container/loom/dye_slot");
    public static final ResourceLocation PATTERN_SLOT = ResourceLocation.withDefaultNamespace("container/loom/pattern_slot");
    public static final ResourceLocation POINTER = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/pointer");
    public static final ResourceLocation SMALL_POINTER = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/small_pointer");
    public static final ResourceLocation UNSELECT_HIGHLIGHTED = ResourceLocation.withDefaultNamespace("transferable_list/unselect_highlighted");
    public static final ResourceLocation UNSELECT = ResourceLocation.withDefaultNamespace("transferable_list/unselect");
    public static final ResourceLocation CRAFTING_2_SLOTS_SELECTION = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/crafting_2_slots_selection");
    public static final ResourceLocation CRAFTING_SELECTION = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/crafting_selection");
    public static final ResourceLocation PACK_HIGHLIGHTED = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/pack_highlighted");
    public static final ResourceLocation PACK_SELECTED = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID, "widget/pack_selected");
    public static final ResourceLocation MAP_PLAYER = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"icon/map/player");
    public static final ResourceLocation SCROLL_DOWN = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/scroll_down");
    public static final ResourceLocation SCROLL_UP = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/scroll_up");
    public static final ResourceLocation SCROLL_RIGHT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/scroll_right");
    public static final ResourceLocation SCROLL_LEFT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/scroll_left");
    public static final ResourceLocation LOADING_BACKGROUND = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/loading_background");
    public static final ResourceLocation LOADING_BAR = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"widget/loading_bar");
    public static final ResourceLocation SADDLE_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/saddle_slot");
    public static final ResourceLocation LLAMA_ARMOR_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/llama_armor_slot");
    public static final ResourceLocation ARMOR_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/armor_slot");
    public static final ResourceLocation HOTBAR_SELECTION = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"hud/hotbar_selection");
    public static final ResourceLocation EXPERIENCE_BAR_BACKGROUND = ResourceLocation.withDefaultNamespace("hud/experience_bar_background");
    public static final ResourceLocation EXPERIENCE_BAR_CURRENT = ResourceLocation.withDefaultNamespace("hud/experience_bar_progress");
    public static final ResourceLocation EXPERIENCE_BAR_RESULT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/experience_bar_result");
    public static final ResourceLocation PADLOCK = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/padlock");
    public static final ResourceLocation BEACON_1 = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/beacon_1");
    public static final ResourceLocation BEACON_2 = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/beacon_2");
    public static final ResourceLocation BEACON_3 = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/beacon_3");
    public static final ResourceLocation BEACON_4 = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/beacon_4");
    public static final ResourceLocation SHIELD_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/shield_slot");
    public static final ResourceLocation FULL_ARROW = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/full_arrow");
    public static final ResourceLocation SMALL_ARROW = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/small_arrow");
    public static final ResourceLocation LIT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/lit");
    public static final ResourceLocation LIT_PROGRESS = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/lit_progress");
    public static final ResourceLocation BREWING_SLOTS = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/brewing_slots");
    public static final ResourceLocation BREWING_COIL_FLAME = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/brewing_coil_flame");
    public static final ResourceLocation BREWING_FUEL_SLOT = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/brewing_fuel_slot");
    public static final ResourceLocation ERROR_CROSS = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/error_cross");
    public static final ResourceLocation ANVIL_HAMMER = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/anvil_hammer");
    public static final ResourceLocation SMITHING_HAMMER = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/smithing_hammer");
    public static final ResourceLocation COMBINER_PLUS = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/combiner_plus");
    public static final ResourceLocation ARROW = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/arrow");
    public static final ResourceLocation CARTOGRAPHY_TABLE = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/cartography_table_empty");
    public static final ResourceLocation CARTOGRAPHY_TABLE_MAP = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/cartography_table_map");
    public static final ResourceLocation CARTOGRAPHY_TABLE_COPY = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/cartography_table_copy");
    public static final ResourceLocation CARTOGRAPHY_TABLE_LOCKED = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/cartography_table_glass");
    public static final ResourceLocation CARTOGRAPHY_TABLE_ZOOM = ResourceLocation.fromNamespaceAndPath(Legacy4J.MOD_ID,"container/cartography_table_zoom");
    public static final ResourceLocation JOIN_HIGHLIGHTED = ResourceLocation.withDefaultNamespace("server_list/join_highlighted");
    public static final ResourceLocation JOIN = ResourceLocation.withDefaultNamespace("server_list/join");
    public static final ResourceLocation MOVE_UP_HIGHLIGHTED = ResourceLocation.withDefaultNamespace("server_list/move_up_highlighted");
    public static final ResourceLocation MOVE_UP = ResourceLocation.withDefaultNamespace("server_list/move_up");
    public static final ResourceLocation MOVE_DOWN_HIGHLIGHTED = ResourceLocation.withDefaultNamespace("server_list/move_down_highlighted");
    public static final ResourceLocation MOVE_DOWN = ResourceLocation.withDefaultNamespace("server_list/move_down");
    public static final ResourceLocation TRANSFER_MOVE_UP_HIGHLIGHTED = ResourceLocation.withDefaultNamespace("transferable_list/move_up_highlighted");
    public static final ResourceLocation TRANSFER_MOVE_UP = ResourceLocation.withDefaultNamespace("transferable_list/move_up");
    public static final ResourceLocation TRANSFER_MOVE_DOWN_HIGHLIGHTED = ResourceLocation.withDefaultNamespace("transferable_list/move_down_highlighted");
    public static final ResourceLocation TRANSFER_MOVE_DOWN = ResourceLocation.withDefaultNamespace("transferable_list/move_down");

}
